---
title: "COMPSCIX 415.2 Homework 1"
author: "Kathleen Welch"
date: "January 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
My Github repository for my assignments can be found at this URL: https://github.com/ktywelch/compscix-415-2-assignments.git

```{r load_packages, warning=FALSE, message=FALSE} 
library(mdsr)
library(tidyverse)
data("WorldCities")
?WorldCities
glimpse(WorldCities)
WorldCities <- head(WorldCities, 200)
```
Question 2
```{r}
country_col <- WorldCities$country
unique(country_col)

region_col <- WorldCities$region
unique(region_col)

country_col <- select(WorldCities, country)
country_col <- WorldCities %>% select(country)
WorldCities %>% select(region) %>% head(5)
```
Question 3 plot ....
``` {r}
WorldCities %>% ggplot(aes(x = population)) + 
  geom_histogram()

<<<<<<< HEAD

```
Question 4
``` {r}

WorldCities %>% ggplot(aes(x = population)) + 
  geom_histogram()+ggtitle('Population of World Cities')+ xlab('Cities Population')+ ylab('Count of Cities')

=======
>>>>>>> bd412cd8e5a045930ed6c2cb3b4ebf0d3b12eda0

``` 